name: Saschaeschmann
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef9f6'
    - '#101626'
    - '#819280'
    - '#25383f'
    - '#62776e'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
